# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

autodiff_hello <- function(input) {
    .Call('_autodiff2r_autodiff_hello', PACKAGE = 'autodiff2r', input)
}

rcppeigen_hello_world <- function() {
    .Call('_autodiff2r_rcppeigen_hello_world', PACKAGE = 'autodiff2r')
}

rcppeigen_outerproduct <- function(x) {
    .Call('_autodiff2r_rcppeigen_outerproduct', PACKAGE = 'autodiff2r', x)
}

rcppeigen_innerproduct <- function(x) {
    .Call('_autodiff2r_rcppeigen_innerproduct', PACKAGE = 'autodiff2r', x)
}

rcppeigen_bothproducts <- function(x) {
    .Call('_autodiff2r_rcppeigen_bothproducts', PACKAGE = 'autodiff2r', x)
}

