# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

autodiff_single_var <- function(input) {
    .Call('_Rcppautodiff_autodiff_single_var', PACKAGE = 'Rcppautodiff', input)
}

rcppeigen_hello_world <- function() {
    .Call('_Rcppautodiff_rcppeigen_hello_world', PACKAGE = 'Rcppautodiff')
}

rcppeigen_outerproduct <- function(x) {
    .Call('_Rcppautodiff_rcppeigen_outerproduct', PACKAGE = 'Rcppautodiff', x)
}

rcppeigen_innerproduct <- function(x) {
    .Call('_Rcppautodiff_rcppeigen_innerproduct', PACKAGE = 'Rcppautodiff', x)
}

rcppeigen_bothproducts <- function(x) {
    .Call('_Rcppautodiff_rcppeigen_bothproducts', PACKAGE = 'Rcppautodiff', x)
}

